"""设备 profile 元数据（channel / state / event 定义表）管理。

ProfileStore 按 ``hw_type`` 分桶保存 DEFINE 表，支持：
- 运行时由 FrameReceiverV2 下发的 DEFINE 帧写入（`apply_channel/state/event_define`）
- 启动时从本地缓存 `~/.satellite_debug_tool/profiles/*.json` 读回（`load_cached`）
- 手动导入/导出（便于离线分析 .sdb）
"""

from .models import DeviceProfile
from .profile_store import ProfileStore
from .cache import ProfileCache, DEFAULT_CACHE_DIR
from .semantics import (
    CHANNEL_ROLE_ANTENNA_AZ,
    CHANNEL_ROLE_ANTENNA_EL,
    CHANNEL_ROLE_GPS_ALT,
    CHANNEL_ROLE_GPS_LAT,
    CHANNEL_ROLE_GPS_LON,
    CHANNEL_ROLE_GPS_COG,
    CHANNEL_ROLE_GPS_COG_STD,
    CHANNEL_ROLE_GPS_NUM_SV,
    CHANNEL_ROLE_GPS_SPEED,
    CHANNEL_ROLE_GPS_VEL_D,
    CHANNEL_ROLE_GPS_VEL_E,
    CHANNEL_ROLE_GPS_VEL_N,
    CHANNEL_ROLE_PITCH,
    CHANNEL_ROLE_POINTING_ERROR,
    CHANNEL_ROLE_ROLL,
    CHANNEL_ROLE_SNR,
    CHANNEL_ROLE_TARGET_AZ,
    CHANNEL_ROLE_TARGET_EL,
    CHANNEL_ROLE_YAW,
    CONTROL_SUBCMD_SET_TRACE_MODE,
    CONTROL_VALUE_FROM_ENUM_VALUE,
    STATE_ROLE_GPS_FIX,
    STATE_ROLE_INS_READY,
    STATE_ROLE_INS_STATUS,
    STATE_ROLE_LOCK_FLAG,
    STATE_ROLE_MODEM_CONNECTED,
    STATE_ROLE_PLL_LOCKED,
    STATE_ROLE_TRACE_MODE,
    ChannelSemantic,
    ControlBinding,
    ProfileSemantics,
    StateSemantic,
)

__all__ = [
    "DeviceProfile", "ProfileStore", "ProfileCache", "DEFAULT_CACHE_DIR",
    "CHANNEL_ROLE_ANTENNA_AZ", "CHANNEL_ROLE_ANTENNA_EL",
    "CHANNEL_ROLE_GPS_ALT", "CHANNEL_ROLE_GPS_LAT", "CHANNEL_ROLE_GPS_LON",
    "CHANNEL_ROLE_GPS_COG", "CHANNEL_ROLE_GPS_COG_STD",
    "CHANNEL_ROLE_GPS_NUM_SV", "CHANNEL_ROLE_GPS_SPEED",
    "CHANNEL_ROLE_GPS_VEL_D", "CHANNEL_ROLE_GPS_VEL_E",
    "CHANNEL_ROLE_GPS_VEL_N",
    "CHANNEL_ROLE_PITCH", "CHANNEL_ROLE_POINTING_ERROR", "CHANNEL_ROLE_ROLL",
    "CHANNEL_ROLE_SNR", "CHANNEL_ROLE_TARGET_AZ", "CHANNEL_ROLE_TARGET_EL",
    "CHANNEL_ROLE_YAW",
    "CONTROL_SUBCMD_SET_TRACE_MODE", "CONTROL_VALUE_FROM_ENUM_VALUE",
    "STATE_ROLE_GPS_FIX", "STATE_ROLE_INS_READY", "STATE_ROLE_INS_STATUS",
    "STATE_ROLE_LOCK_FLAG", "STATE_ROLE_MODEM_CONNECTED",
    "STATE_ROLE_PLL_LOCKED", "STATE_ROLE_TRACE_MODE",
    "ChannelSemantic", "ControlBinding", "ProfileSemantics", "StateSemantic",
]
