"""DEBUG telemetry, profile, parameter, OTA, and GNSS domain."""

from __future__ import annotations

from types import MappingProxyType

from ..codec_v2 import (
    build_channel_enable_mask,
    build_debug_enable_v2,
    build_device_reboot,
    build_ota_abort,
    build_ota_begin,
    build_ota_data,
    build_ota_end,
    build_para_reset,
    build_para_set,
    build_request_channel_define,
    build_request_event_define,
    build_request_meta_info,
    build_request_para_table,
    build_request_profile_semantics,
    build_request_state_define,
    build_reset_stats,
    build_set_sample_rate,
    build_set_trace_mode,
    build_user_mark,
    decode_channel_define,
    decode_command_response,
    decode_data_report,
    decode_event_define,
    decode_event_report,
    decode_gnss_cnr_report,
    decode_gnss_sat_report,
    decode_gnss_signal_report,
    decode_gnss_sky_report,
    decode_heartbeat,
    decode_meta_info,
    decode_para_table_report,
    decode_profile_semantics,
    decode_state_define,
    decode_state_report,
)
from ..frame_v2 import (
    ChannelDefineTable,
    CommandResponse,
    CmdType,
    DataReport,
    EventDefineTable,
    EventReport,
    GnssCnrReport,
    GnssSatReport,
    GnssSignalReport,
    GnssSkyReport,
    Heartbeat,
    MetaInfo,
    ParaTableReport,
    ProfileSemanticsReport,
    StateDefineTable,
    StateReport,
)


DECODERS = MappingProxyType({
    int(CmdType.DATA_REPORT): decode_data_report,
    int(CmdType.COMMAND_RESPONSE): decode_command_response,
    int(CmdType.META_INFO): decode_meta_info,
    int(CmdType.CHANNEL_DEFINE): decode_channel_define,
    int(CmdType.STATE_DEFINE): decode_state_define,
    int(CmdType.EVENT_DEFINE): decode_event_define,
    int(CmdType.STATE_REPORT): decode_state_report,
    int(CmdType.EVENT_REPORT): decode_event_report,
    int(CmdType.HEARTBEAT): decode_heartbeat,
    int(CmdType.PARA_TABLE_REPORT): decode_para_table_report,
    int(CmdType.PROFILE_SEMANTICS): decode_profile_semantics,
    int(CmdType.GNSS_SKY_REPORT): decode_gnss_sky_report,
    int(CmdType.GNSS_CNR_REPORT): decode_gnss_cnr_report,
    int(CmdType.GNSS_SAT_REPORT): decode_gnss_sat_report,
    int(CmdType.GNSS_SIGNAL_REPORT): decode_gnss_signal_report,
})


__all__ = [
    "DECODERS",
    "ChannelDefineTable",
    "CommandResponse",
    "DataReport",
    "EventDefineTable",
    "EventReport",
    "GnssCnrReport",
    "GnssSatReport",
    "GnssSignalReport",
    "GnssSkyReport",
    "Heartbeat",
    "MetaInfo",
    "ParaTableReport",
    "ProfileSemanticsReport",
    "StateDefineTable",
    "StateReport",
    "build_channel_enable_mask",
    "build_debug_enable_v2",
    "build_device_reboot",
    "build_ota_abort",
    "build_ota_begin",
    "build_ota_data",
    "build_ota_end",
    "build_para_reset",
    "build_para_set",
    "build_request_channel_define",
    "build_request_event_define",
    "build_request_meta_info",
    "build_request_para_table",
    "build_request_profile_semantics",
    "build_request_state_define",
    "build_reset_stats",
    "build_set_sample_rate",
    "build_set_trace_mode",
    "build_user_mark",
]
