"""DEBUG 协议 v2 公开接口。"""

from .crc16 import Crc16
from .codec_v2 import (
    CodecError,
    build_frame,
    build_control,
    build_debug_enable_v2,
    build_request_meta_info,
    build_request_channel_define,
    build_request_state_define,
    build_request_event_define,
    build_request_profile_semantics,
    build_user_mark,
    build_set_sample_rate,
    build_set_trace_mode,
    build_channel_enable_mask,
    build_reset_stats,
    # M9: 参数管理 + OTA
    build_request_para_table,
    build_para_set,
    build_para_reset,
    build_ota_begin,
    build_ota_data,
    build_ota_end,
    build_ota_abort,
    build_device_reboot,
    build_service_subscribe,
    build_service_set_control_mode,
    build_service_apply_rf,
    build_service_set_tx_enable,
    build_service_set_capture_profile,
    ORBIT_SCHEMA_VERSION,
    ORBIT_UPLOAD_CHUNK_MAX,
    ORBIT_FEATURE_SKY_SNAPSHOT,
    build_orbit_capabilities,
    build_orbit_scan,
    build_orbit_catalog,
    build_orbit_current,
    build_orbit_sky_snapshot,
    build_orbit_predict,
    build_orbit_prediction_page,
    build_orbit_select,
    build_orbit_upload_begin,
    build_orbit_upload_chunk,
    build_orbit_upload_end,
    build_orbit_upload_abort,
    decode_para_table_report,
    decode_profile_semantics,
    decode_gnss_sky_report,
    decode_gnss_cnr_report,
    decode_gnss_sat_report,
    decode_gnss_signal_report,
    decode_service_identity,
    decode_service_hardware_identity,
    decode_service_navigation_source_info,
    decode_service_external_ins_diagnostics,
    decode_service_link_detail,
    decode_service_rf_lock_status,
    decode_service_fast_state,
    decode_service_slow_state,
    decode_service_component_health,
    decode_service_capabilities,
    decode_service_control_response,
    decode_orbit_report,
)
from .frame_receiver_v2 import FrameReceiverV2
from .frame_v2 import (
    PROTOCOL_VERSION,
    FRAME_HEADER_0, FRAME_HEADER_1, FRAME_FOOTER, DEVICE_TYPE,
    MAX_DATA_LENGTH, MAX_FRAME_LENGTH,
    CHANNEL_ID_MAX, STATE_ID_MAX,
    EVENT_ID_MIN, EVENT_ID_MAX, EVENT_ID_USER_MARK,
    DATA_REPORT_MAX_CHANNELS, EVENT_PAYLOAD_MAX,
    CHANNEL_FLAG_DEFAULT_VISIBLE, CHANNEL_FLAG_CRITICAL,
    STATE_FLAG_CRITICAL, STATE_FLAG_INVERSE,
    PARA_FLAG_REQUIRES_REBOOT, PARA_FLAG_READ_ONLY,
    CmdType, SubCmd, RespCode, DataType, StateType, Level, ParaType,
    ServiceControlOp, ServiceResultCode, OrbitOperation, OrbitStatus,
    MetaInfo,
    ChannelDefEntry, ChannelDefineTable,
    StateEnumItem, StateDefEntry, StateDefineTable,
    EventDefEntry, EventDefineTable,
    ChannelSample, DataReport,
    StateSample, StateReport,
    EventReport, Heartbeat, CommandResponse,
    ParaEntry, ParaTableReport,
    ProfileSemanticChannelEntry, ProfileSemanticStateEntry,
    ProfileSemanticCapabilityEntry, ProfileSemanticsReport,
    GnssSkySatellite, GnssSkyReport,
    GnssCnrObservation, GnssCnrReport,
    GnssSatRecord, GnssSatReport,
    GnssSignalRecord, GnssSignalReport,
    ServiceIdentity, ServiceHardwareIdentity, ServiceFastState, ServiceSlowState,
    ServiceNavigationSourceInfo, ServiceExternalInsDiagnostics,
    ServiceLinkDetail, ServiceRfLockStatus,
    ServiceComponentValue, ServiceComponentHealth,
    ServiceCapabilities, ServiceControlResponse,
    OrbitReportHeader, OrbitStatusReport, OrbitCapabilitiesReport,
    OrbitCatalogEntry, OrbitCatalogReport,
    OrbitCurrentSample, OrbitCurrentReport, OrbitSkySample, OrbitSkyReport,
    OrbitPredictionAccepted, OrbitPredictionSample, OrbitPredictionPage,
    OrbitPassSummary, OrbitPassPage, OrbitUploadProgress,
    RawFrame, FrameV2Record,
)


__all__ = [
    # crc
    "Crc16",
    # envelope & builders
    "CodecError",
    "build_frame", "build_control",
    "build_debug_enable_v2",
    "build_request_meta_info", "build_request_channel_define",
    "build_request_state_define", "build_request_event_define",
    "build_request_profile_semantics",
    "build_user_mark", "build_set_sample_rate", "build_set_trace_mode",
    "build_channel_enable_mask", "build_reset_stats",
    "build_request_para_table", "build_para_set", "build_para_reset",
    "build_ota_begin", "build_ota_data", "build_ota_end",
    "build_ota_abort", "build_device_reboot",
    "build_service_subscribe", "build_service_set_control_mode",
    "build_service_apply_rf", "build_service_set_tx_enable",
    "build_service_set_capture_profile",
    "ORBIT_SCHEMA_VERSION", "ORBIT_UPLOAD_CHUNK_MAX", "ORBIT_FEATURE_SKY_SNAPSHOT",
    "build_orbit_capabilities", "build_orbit_scan", "build_orbit_catalog",
    "build_orbit_current", "build_orbit_sky_snapshot", "build_orbit_predict", "build_orbit_prediction_page",
    "build_orbit_select", "build_orbit_upload_begin", "build_orbit_upload_chunk",
    "build_orbit_upload_end",
    "build_orbit_upload_abort",
    "decode_para_table_report", "decode_profile_semantics",
    "decode_gnss_sky_report", "decode_gnss_cnr_report",
    "decode_gnss_sat_report", "decode_gnss_signal_report",
    "decode_service_identity", "decode_service_hardware_identity",
    "decode_service_navigation_source_info", "decode_service_external_ins_diagnostics",
    "decode_service_link_detail", "decode_service_rf_lock_status",
    "decode_service_fast_state",
    "decode_service_slow_state", "decode_service_component_health",
    "decode_service_capabilities", "decode_service_control_response",
    "decode_orbit_report",
    # receiver
    "FrameReceiverV2",
    # constants
    "PROTOCOL_VERSION",
    "FRAME_HEADER_0", "FRAME_HEADER_1", "FRAME_FOOTER", "DEVICE_TYPE",
    "MAX_DATA_LENGTH", "MAX_FRAME_LENGTH",
    "CHANNEL_ID_MAX", "STATE_ID_MAX",
    "EVENT_ID_MIN", "EVENT_ID_MAX", "EVENT_ID_USER_MARK",
    "DATA_REPORT_MAX_CHANNELS", "EVENT_PAYLOAD_MAX",
    "CHANNEL_FLAG_DEFAULT_VISIBLE", "CHANNEL_FLAG_CRITICAL",
    "STATE_FLAG_CRITICAL", "STATE_FLAG_INVERSE",
    "PARA_FLAG_REQUIRES_REBOOT", "PARA_FLAG_READ_ONLY",
    # enums
    "CmdType", "SubCmd", "RespCode", "DataType", "StateType", "Level", "ParaType",
    "ServiceControlOp", "ServiceResultCode", "OrbitOperation", "OrbitStatus",
    # dataclasses
    "MetaInfo",
    "ChannelDefEntry", "ChannelDefineTable",
    "StateEnumItem", "StateDefEntry", "StateDefineTable",
    "EventDefEntry", "EventDefineTable",
    "ChannelSample", "DataReport",
    "StateSample", "StateReport",
    "EventReport", "Heartbeat", "CommandResponse",
    "ParaEntry", "ParaTableReport",
    "ProfileSemanticChannelEntry", "ProfileSemanticStateEntry",
    "ProfileSemanticCapabilityEntry", "ProfileSemanticsReport",
    "GnssSkySatellite", "GnssSkyReport",
    "GnssCnrObservation", "GnssCnrReport",
    "GnssSatRecord", "GnssSatReport",
    "GnssSignalRecord", "GnssSignalReport",
    "ServiceIdentity", "ServiceHardwareIdentity",
    "ServiceNavigationSourceInfo", "ServiceExternalInsDiagnostics",
    "ServiceFastState", "ServiceSlowState", "ServiceLinkDetail",
    "ServiceRfLockStatus",
    "ServiceComponentValue", "ServiceComponentHealth",
    "ServiceCapabilities", "ServiceControlResponse",
    "OrbitReportHeader", "OrbitStatusReport", "OrbitCapabilitiesReport",
    "OrbitCatalogEntry", "OrbitCatalogReport",
    "OrbitCurrentSample", "OrbitCurrentReport", "OrbitSkySample", "OrbitSkyReport",
    "OrbitPredictionAccepted", "OrbitPredictionSample", "OrbitPredictionPage",
    "OrbitPassSummary", "OrbitPassPage", "OrbitUploadProgress",
    "RawFrame", "FrameV2Record",
]
